#!/bin/php -q
<?php
if(!isset($argv[1])) die("Unknown action\n");
$action=$argv[1];

function execute($arg="") {
	//~ echo $arg."\n";
	ob_start();
	passthru($arg);
	$buffer=ob_get_clean();
	$buffer=trim($buffer);
	//~ echo $buffer."\n";
	return $buffer;
}

function get_vol_onoff($temp) {
	$temp=str_replace("\n"," ",$temp);
	$temp=explode(" ",$temp);
	$vol="";
	$onoff="";
	foreach($temp as $val) {
		if(substr($val,0,1)=="[" && substr($val,-1,1)=="]") {
			$val=substr($val,1,-1);
			if(substr($val,-1,1)=="%") {
				$vol=substr($val,0,-1);
			}
			if(in_array($val,array("on","off"))) {
				$onoff=$val;
			}
		}
	}
	return array("vol"=>$vol,"onoff"=>$onoff);
}

function notify_volume($vol) {
	$iconos=array(
		"0"=>"notification-audio-volume-off",
		"10"=>"notification-audio-volume-low",
		"20"=>"notification-audio-volume-low",
		"30"=>"notification-audio-volume-low",
		"40"=>"notification-audio-volume-medium",
		"50"=>"notification-audio-volume-medium",
		"60"=>"notification-audio-volume-medium",
		"70"=>"notification-audio-volume-medium",
		"80"=>"notification-audio-volume-high",
		"90"=>"notification-audio-volume-high",
		"100"=>"notification-audio-volume-high",
	);
	execute("notify-send -t 1000 -i ".$iconos[$vol]." ".$vol."% ·".str_repeat("·",$vol*0.88));
}

function notify_mute() {
	execute("notify-send -t 1000 -i notification-audio-volume-muted MUTE ·");
}

$master=get_vol_onoff(execute("amixer sget Master"));
$capture=get_vol_onoff(execute("amixer sget Capture"));
//~ print_r($master)."\n";
//~ print_r($capture)."\n";

switch($action) {
	case "Up":
		if($master["onoff"]=="on") {
			$master["vol"]=round(min(max($master["vol"]+10,0),100),-1);
			execute("amixer sset Master ".$master["vol"]."%");
			notify_volume($master["vol"]);
		} else {
			notify_mute();
		}
		break;
	case "Down":
		if($master["onoff"]=="on") {
			$master["vol"]=round(min(max($master["vol"]-10,0),100),-1);
			execute("amixer sset Master ".$master["vol"]."%");
			notify_volume($master["vol"]);
		} else {
			notify_mute();
		}
		break;
	case "Mute":
		if($master["onoff"]!=$capture["onoff"]) {
			if($master["onoff"]=="on") execute("amixer sset Master toggle");
			if($capture["onoff"]=="on") execute("amixer sset Capture toggle");
			if($master["onoff"]=="off") notify_mute();
		} else {
			$permutar=array("on"=>"off","off"=>"on");
			$master["onoff"]=$permutar[$master["onoff"]];
			execute("amixer sset Master toggle");
			execute("amixer sset Capture toggle");
			if($master["onoff"]=="off") notify_mute();
			$master["vol"]=round(min(max($master["vol"],0),100),-1);
			if($master["onoff"]=="on") notify_volume($master["vol"]);
		}
		break;
	case "Reset":
		execute("killall pulseaudio");
		execute("sudo setfacl -m \"u:\$USER:rw-\" /dev/snd/*");
		execute("sudo setfacl -m \"u:\$USER:rw-\" /dev/video*");
		execute("pulseaudio --start");
		// PARA INFORMAR
		$master=get_vol_onoff(execute("amixer sget Master"));
		if($master["onoff"]=="on") {
			execute("amixer sset Master ".$master["vol"]."%");
			notify_volume($master["vol"]);
		} else {
			notify_mute();
		}
		break;
}

?>