#!/bin/bash

#pidof mate-screenshot || mate-screenshot -i
ksnip &
for i in $(seq 1 1000); do
	c=$(xdotool search --name ksnip | wc -l)
	j=$(xdotool search --name ksnip | tail -1)
	#~ echo c=$c
	#~ echo j=$j
	if [ "$c" == "3" -a "$j" != "" ]; then
		break;
	fi
	usleep 1000
done
xdotool windowmap $j
xdotool windowfocus $j
