
all:
	gcc -o dtatom2title -I /usr/dt/share/include -L /usr/dt/lib -lXt -lDtSvc -lDtWidget -ltt -lXm -lX11 dtatom2title.c
	gcc -o dtgetallws -I /usr/dt/share/include -L /usr/dt/lib -lXt -lDtSvc -lDtWidget -ltt -lXm -lX11 dtgetallws.c
	gcc -o dtgetcurws -I /usr/dt/share/include -L /usr/dt/lib -lXt -lDtSvc -lDtWidget -ltt -lXm -lX11 dtgetcurws.c

